### ISSUE TITLE
TypeError: this.clients[lockID].logout is not a function

### ISSUE THREAD

**Issue by MarcMagnin** [luisrudge/next.js-auth0#15]
Hi,

First: thanks for that smart exemple!
When logging out I got the following error: 
```
TypeError: this.clients[lockID].logout is not a function
    at Auth0WebAPI.signOut (http://192.168.0.49:3000/_next/webpack/0.da60b0065dcde4baada3.hot-update.js:3758:26)
    at Auth0Lock.logout (http://192.168.0.49:3000/_next/webpack/0.da60b0065dcde4baada3.hot-update.js:13533:23)
    at logout (http://192.168.0.49:3000/_next/-/page/auth/sign-off:164:20)
    at SignOff.componentDidMount (http://192.168.0.49:3000/_next/-/page/auth/sign-off:61:24)
    at SignOff.proxiedComponentDidMount (http://192.168.0.49:3000/_next/-/commons.js:35049:40)
    at http://192.168.0.49:3000/_next/-/commons.js:26879:25
    at measureLifeCyclePerf (http://192.168.0.49:3000/_next/-/commons.js:26689:12)
    at http://192.168.0.49:3000/_next/-/commons.js:26878:11
    at CallbackQueue.notifyAll (http://192.168.0.49:3000/_next/-/commons.js:11852:22)
    at ReactReconcileTransaction.close (http://192.168.0.49:3000/_next/-/commons.js:31772:26)
```
Many thanks for your help!

**Comment by luisrudge** [comment]
You have to update Lock to the latest version. Can you send a PR with that?

**Comment by MarcMagnin** [comment]
Yey, installing yarn and I'll send a PR ;)
