### ISSUE TITLE
build command doesn't work

### ISSUE THREAD

**Issue by cyrus-za** [luisrudge/next.js-auth0#18]
# command `yarn build` does not work

- OS: Windows 10 Pro
- npm version: 5.0.0
- yarn version 0.24.4
- node version  8.0.0

I cloned the repo, ran `yarn` followed by `yarn build` and got the following error

```
~\playground\nextnext.js-auth0>yarn build
yarn build v0.24.4
$ next build
> Using external babel configuration
> location: "~\playground\nextnext.js-auth0\.babelrc"
> Failed to build on ~\usr\Local\Temp\db1da299-90f1-451b-8211-c205e1fc5d01
{ Error: ./~/react-addons-css-transition-group/index.js
Module not found: Error: Can't resolve 'react/lib/ReactCSSTransitionGroup' in '~\playground\nextnext.js-auth0\node_modules\react-addons-css-transition-group'
resolve 'react/lib/ReactCSSTransitionGroup' in '~\playground\nextnext.js-auth0\node_modules\react-addons-css-transition-group'
  Parsed request is a module
  using description file: ~\playground\nextnext.js-auth0\node_modules\react-addons-css-transition-group\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    aliased with mapping 'react': '~\playground\nextnext.js-auth0\node_modules\react\dist\react.min.js' to '~\playground\nextnext.js-auth0\node_modules\react\dist\react.min.js/lib/ReactCSSTransitionGroup'
      using description file: ~\playground\nextnext.js-auth0\node_modules\react-addons-css-transition-group\package.json (relative path: .)
        Field 'browser' doesn't contain a valid alias configuration
      after using description file: ~\playground\nextnext.js-auth0\node_modules\react-addons-css-transition-group\package.json (relative path: .)
        using description file: ~\playground\nextnext.js-auth0\node_modules\react\package.json (relative path: ./dist/react.min.js/lib/ReactCSSTransitionGroup)
          as directory
            ~\playground\nextnext.js-auth0\node_modules\react\dist\react.min.js\lib\ReactCSSTransitionGroup doesn't exist
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            ~\playground\nextnext.js-auth0\node_modules\react\dist\react.min.js\lib\ReactCSSTransitionGroup doesn't exist
          .js
            Field 'browser' doesn't contain a valid alias configuration
            ~\playground\nextnext.js-auth0\node_modules\react\dist\react.min.js\lib\ReactCSSTransitionGroup.js doesn't exist
          .json
            Field 'browser' doesn't contain a valid alias configuration
            ~\playground\nextnext.js-auth0\node_modules\react\dist\react.min.js\lib\ReactCSSTransitionGroup.json doesn't exist
[~\playground\nextnext.js-auth0\node_modules\react\dist\react.min.js\lib\ReactCSSTransitionGroup]
[~\playground\nextnext.js-auth0\node_modules\react\dist\react.min.js\lib\ReactCSSTransitionGroup]
[~\playground\nextnext.js-auth0\node_modules\react\dist\react.min.js\lib\ReactCSSTransitionGroup.js]
[~\playground\nextnext.js-auth0\node_modules\react\dist\react.min.js\lib\ReactCSSTransitionGroup.json]
  @ ./~/react-addons-css-transition-group/index.js 1:17-61
  @ ./~/auth0-lock/lib/ui/box/chrome.js
  @ ./~/auth0-lock/lib/ui/box/container.js
  @ ./~/auth0-lock/lib/core/actions.js
  @ ./~/auth0-lock/lib/core.js
  @ ./~/auth0-lock/lib/index.js
  @ ./utils/lock.js
  @ ./pages/auth/sign-off.js?entry
  @ multi ./pages/auth/sign-off.js?entry
    at ~\playground\nextnext.js-auth0\node_modules\next\dist\server\build\index.js:181:21
    at ~\playground\nextnext.js-auth0\node_modules\webpack\lib\Compiler.js:267:15
    at Compiler.emitRecords (~\playground\nextnext.js-auth0\node_modules\webpack\lib\Compiler.js:362:37)
    at ~\playground\nextnext.js-auth0\node_modules\webpack\lib\Compiler.js:260:12
    at ~\playground\nextnext.js-auth0\node_modules\webpack\lib\Compiler.js:355:11
    at next (~\playground\nextnext.js-auth0\node_modules\tapable\lib\Tapable.js:154:11)
    at Compiler.compiler.plugin (~\playground\nextnext.js-auth0\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (~\playground\nextnext.js-auth0\node_modules\tapable\lib\Tapable.js:158:13)
    at Compiler.afterEmit (~\playground\nextnext.js-auth0\node_modules\webpack\lib\Compiler.js:352:8)
    at Compiler.<anonymous> (~\playground\nextnext.js-auth0\node_modules\webpack\lib\Compiler.js:347:14)
    errors: [ './~/react-addons-css-transition-group/index.js\nModule not found: Error: Can\'t resolve \'react/lib/ReactCSSTransitionGroup\' in \'~\\playground\\next.js-auth0\\node_modules\\react-addons-css-transition-group\'\nresolve \'react/lib/ReactCSSTransitionGroup\' in \'~\\playground\\next.js-auth0\\node_modules\\react-addons-css-transition-group\'\n  Parsed request is a module\n  using description file: ~\\playground\\next.js-auth0\\node_modules\\react-addons-css-transition-group\\package.json (relative path: .)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n    aliased with mapping \'react\': \'~\\playground\\next.js-auth0\\node_modules\\react\\dist\\react.min.js\' to \'~\\playground\\next.js-auth0\\node_modules\\react\\dist\\react.min.js/lib/ReactCSSTransitionGroup\'\n      using description file: ~\\playground\\next.js-auth0\\node_modules\\react-addons-css-transition-group\\package.json (relative path: .)\n        Field \'browser\' doesn\'t contain a valid alias configuration\n      after using description file: ~\\playground\\next.js-auth0\\node_modules\\react-addons-css-transition-group\\package.json (relative path: .)\n        using description file: ~\\playground\\next.js-auth0\\node_modules\\react\\package.json (relative path: ./dist/react.min.js/lib/ReactCSSTransitionGroup)\n          as directory\n            ~\\playground\\next.js-auth0\\node_modules\\react\\dist\\react.min.js\\lib\\ReactCSSTransitionGroup doesn\'t exist\n          no extension\n            Field \'browser\' doesn\'t contain a valid alias configuration\n            ~\\playground\\next.js-auth0\\node_modules\\react\\dist\\react.min.js\\lib\\ReactCSSTransitionGroup doesn\'t exist\n          .js\n            Field \'browser\' doesn\'t contain a valid alias configuration\n            ~\\playground\\next.js-auth0\\node_modules\\react\\dist\\react.min.js\\lib\\ReactCSSTransitionGroup.js doesn\'t exist\n          .json\n            Field \'browser\' doesn\'t contain a valid alias configuration\n            ~\\playground\\next.js-auth0\\node_modules\\react\\dist\\react.min.js\\lib\\ReactCSSTransitionGroup.json doesn\'t exist\n[~\\playground\\next.js-auth0\\node_modules\\react\\dist\\react.min.js\\lib\\ReactCSSTransitionGroup]\n[~\\playground\\next.js-auth0\\node_modules\\react\\dist\\react.min.js\\lib\\ReactCSSTransitionGroup]\n[~\\playground\\next.js-auth0\\node_modules\\react\\dist\\react.min.js\\lib\\ReactCSSTransitionGroup.js]\n[~\\playground\\next.js-auth0\\node_modules\\react\\dist\\react.min.js\\lib\\ReactCSSTransitionGroup.json]\n @ ./~/react-addons-css-transition-group/index.js 1:17-61\n @ ./~/auth0-lock/lib/ui/box/chrome.js\n @ ./~/auth0-lock/lib/ui/box/container.js\n @ ./~/auth0-lock/lib/core/actions.js\n @ ./~/auth0-lock/lib/core.js\n @ ./~/auth0-lock/lib/index.js\n @ ./utils/lock.js\n @ ./pages/auth/sign-off.js?entry\n @ multi ./pages/auth/sign-off.js?entry' ],
    warnings: [] }
error Command failed with exit code 1.
```

**Comment by cyrus-za** [comment]
nevermind. Seems like this was logged already in nextjs repo with a fix in config logged there. https://github.com/zeit/next.js/issues/1951
